cmake_minimum_required(VERSION 3.0.2)
project(camera_model)

set(CMAKE_BUILD_TYPE Debug)

execute_process(COMMAND lsb_release -cs
    OUTPUT_VARIABLE LSB_RELEASE_ID_SHORT
)

if(${LSB_RELEASE_ID_SHORT} MATCHES "bionic")
  set(CMAKE_CXX_STANDARD_REQUIRED 11)
  message("-- Systemm version: ${LSB_RELEASE_ID_SHORT}, set to C++11")
elseif(${LSB_RELEASE_ID_SHORT} MATCHES "focal")
  set(CMAKE_CXX_STANDARD_REQUIRED 14)
  message("-- Systemm version: ${LSB_RELEASE_ID_SHORT}, set to C++14")
endif()
set (CMAKE_EXE_LINKER_FLAGS "-lboost_filesystem")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -Wall -fPIC -fopenmp")

find_package(catkin REQUIRED COMPONENTS
    roscpp
    std_msgs
    sensor_msgs
    cv_bridge
    message_generation
    )


if(${LSB_RELEASE_ID_SHORT} MATCHES "bionic")
 find_package(Boost 1.65.1 EXACT REQUIRED COMPONENTS filesystem program_options system)
elseif(${LSB_RELEASE_ID_SHORT} MATCHES "focal")
 find_package(Boost REQUIRED COMPONENTS filesystem program_options system)
endif()
include_directories(${Boost_INCLUDE_DIRS})

find_package(OpenCV REQUIRED)

#set(EIGEN_INCLUDE_DIR "/usr/local/include/eigen3")
find_package(Ceres REQUIRED)
include_directories(${CERES_INCLUDE_DIRS})

message(STATUS "OpenCV library status:")
message(STATUS "    version: ${OpenCV_VERSION}")
message(STATUS "    libraries: ${OpenCV_LIBS}")
message(STATUS "    include path: ${OpenCV_INCLUDE_DIRS}")
message(STATUS "Eigen library path: ${EIGEN3_INCLUDE_DIR}")

add_message_files(
    FILES
    CalibrationProgress.msg
)

add_service_files(
    FILES
    CalibrationControl.srv
)

generate_messages(
    DEPENDENCIES
    std_msgs
)

catkin_package(
    INCLUDE_DIRS include
    LIBRARIES camera_model
    CATKIN_DEPENDS roscpp std_msgs sensor_msgs cv_bridge message_runtime
#    DEPENDS system_lib
    )

include_directories(
    ${catkin_INCLUDE_DIRS}
     )

include_directories("include")

aux_source_directory(${PROJECT_SOURCE_DIR}/src/apriltag AprilTagSrc)
aux_source_directory(${PROJECT_SOURCE_DIR}/src/apriltag_frontend AprilTagSrc2)

set(CAMERA_MODEL_FILES
    ${PROJECT_SOURCE_DIR}/src/camera_models/Camera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/CostFunctionFactory.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/CameraFactory.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/PinholeCamera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/PinholeFullCamera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/CataCamera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/EquidistantCamera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/ScaramuzzaCamera.cc
    ${PROJECT_SOURCE_DIR}/src/camera_models/PolyFisheyeCamera.cpp
    ${PROJECT_SOURCE_DIR}/src/camera_models/SplineCamera.cpp
    ${PROJECT_SOURCE_DIR}/src/camera_models/FovCamera.cpp
    ${PROJECT_SOURCE_DIR}/src/sparse_graph/Transform.cc
    ${PROJECT_SOURCE_DIR}/src/gpl/gpl.cc
    ${PROJECT_SOURCE_DIR}/src/code_utils/math_utils/Polynomial.cpp
    ${PROJECT_SOURCE_DIR}/src/code_utils/cv_utils.cc
    ${PROJECT_SOURCE_DIR}/src/gpl/EigenQuaternionParameterization.cc
    ${AprilTagSrc}
    ${AprilTagSrc2}
    )

set(CALIB_ROUTINE_FILES
    ${PROJECT_SOURCE_DIR}/src/calib_routine/calib_utils.cpp
    ${PROJECT_SOURCE_DIR}/src/calib_routine/calibration_config.cpp
    ${PROJECT_SOURCE_DIR}/src/calib_routine/calibration_target_detector.cpp
    ${PROJECT_SOURCE_DIR}/src/calib_routine/intrinsics_calibration_routine.cpp
    )

add_executable(calibration_node
    src/calib_routine/calibration_node.cpp
    src/calib/CameraCalibration.cc
    ${CALIB_ROUTINE_FILES}
    ${CAMERA_MODEL_FILES}
    )

add_dependencies(calibration_node 
    ${${PROJECT_NAME}_EXPORTED_TARGETS} 
    ${catkin_EXPORTED_TARGETS}
    )

add_executable(Calibration 
    src/intrinsic_calib.cc
    src/chessboard/Chessboard.cc
    src/calib/CameraCalibration.cc
    ${CAMERA_MODEL_FILES}
    )

add_executable(april_calib
    src/april_calib.cc
    src/chessboard/Chessboard.cc
    src/calib/CameraCalibration.cc
    ${CAMERA_MODEL_FILES}
    )

 add_executable(Test
     src/test_calib.cc
     src/chessboard/Chessboard.cc
     src/calib/CameraCalibrationTest.cc
     ${CAMERA_MODEL_FILES}
     )

add_library(camera_model STATIC
    src/chessboard/Chessboard.cc
    src/calib/CameraCalibration.cc
    ${CAMERA_MODEL_FILES}
    )

target_link_libraries(calibration_node
    ${catkin_LIBRARIES}
    ${Boost_LIBRARIES}
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
    dw    )
target_link_libraries(Calibration
    ${Boost_LIBRARIES}
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
    dw    )
target_link_libraries(april_calib
    ${Boost_LIBRARIES}
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
    dw    )
target_link_libraries(Test
    ${Boost_LIBRARIES}
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES}
     dw    )
target_link_libraries(camera_model
    ${Boost_LIBRARIES}
    ${OpenCV_LIBS}
    ${CERES_LIBRARIES} )



